import type { Candidate, DailyRun, Project } from "@/lib/types";

export const demoProjects: Project[] = [
  {
    id: "project_northstar",
    name: "Northstar",
    domain: "northstar.so",
    founderName: "Maya Chen",
    agentName: "Kit",
    inboxId: "kit@northstar.so",
    status: "ready",
    knowledgeVersion: 4,
    exclusions: {
      keywords: ["crypto", "gambling", "enterprise hardware"],
      domains: ["google.com", "microsoft.com"],
      categories: ["Web3"],
      notes: "Skip agencies and products without a public website.",
      cooldownDays: 90,
    },
  },
  {
    id: "project_papertrail",
    name: "Papertrail",
    domain: "papertrail.studio",
    founderName: "Noah Williams",
    agentName: "Milo",
    inboxId: "milo@papertrail.studio",
    status: "ready",
    knowledgeVersion: 2,
    exclusions: {
      keywords: ["consumer games"],
      domains: [],
      categories: [],
      notes: "",
      cooldownDays: 60,
    },
  },
];

export const demoCandidates: Candidate[] = [
  {
    id: "candidate_attio",
    projectId: "project_northstar",
    name: "Mori",
    tagline: "Customer research that keeps itself current",
    productHuntUrl: "https://www.producthunt.com/posts/mori-research",
    websiteUrl: "https://mori.so",
    companyContext:
      "Mori turns interview notes and support conversations into a continuously updated customer evidence library for product teams.",
    recipientEmail: "hello@mori.so",
    emailConfidence: 0.94,
    emailEvidenceUrl: "https://mori.so/contact",
    alternativeEmails: ["team@mori.so"],
    matchReason:
      "Their evidence library complements Northstar’s lightweight roadmap ritual for early product teams.",
    subject: "A small idea for Mori’s research loop",
    body: "Hi Mori team,\n\nI’m Kit, Maya’s AI agent at Northstar. I noticed Mori keeps evidence connected to the decisions it informs, instead of turning interviews into another static repository.\n\nNorthstar helps small product teams turn that same evidence into a weekly roadmap rhythm. Maya thought a short field guide connecting the two workflows might be useful to your audience.\n\nWould you be open to a quick note with the outline?\n\nKit",
    status: "ready",
  },
  {
    id: "candidate_harbor",
    projectId: "project_northstar",
    name: "Harbor",
    tagline: "A calmer home for customer-facing release notes",
    productHuntUrl: "https://www.producthunt.com/posts/harbor-notes",
    websiteUrl: "https://harbor.page",
    companyContext:
      "Harbor lets small software teams publish targeted release notes and close the loop with customers who requested a feature.",
    recipientEmail: "founders@harbor.page",
    emailConfidence: 0.87,
    emailEvidenceUrl: "https://harbor.page/about",
    alternativeEmails: [],
    matchReason:
      "Harbor’s request-to-release loop reaches the same founder-led product teams Northstar serves.",
    subject: "The loop after a Harbor update",
    body: "Hi Harbor team,\n\nI’m Kit, Maya’s AI agent at Northstar. Your request-to-release links stood out because they show customers exactly where an update came from, not just what shipped.\n\nNorthstar helps founder-led teams make the prioritization step before that update visible and repeatable. Maya has a compact roadmap ritual that could pair well with Harbor’s workflow.\n\nWorth sending over the one-page version?\n\nKit",
    status: "ready",
  },
  {
    id: "candidate_plain",
    projectId: "project_northstar",
    name: "Plainly",
    tagline: "Turn product decisions into clear internal updates",
    productHuntUrl: "https://www.producthunt.com/posts/plainly",
    websiteUrl: "https://plainly.work",
    companyContext:
      "Plainly converts issue and roadmap activity into concise stakeholder updates without another meeting.",
    recipientEmail: "team@plainly.work",
    emailConfidence: 0.78,
    emailEvidenceUrl: "https://plainly.work",
    alternativeEmails: ["support@plainly.work"],
    matchReason:
      "Both products reduce coordination overhead around product decisions, but at adjacent stages.",
    subject: "Before the Plainly update goes out",
    body: "Hi Plainly team,\n\nI’m Kit, Maya’s AI agent at Northstar. I saw that Plainly turns roadmap activity into stakeholder updates without asking product managers to rewrite the week.\n\nNorthstar gives small teams a lightweight decision record before those updates are created. Maya thinks the handoff between the two could make a practical short guide for teams drowning in status work.\n\nShould I send the rough outline?\n\nKit",
    status: "ready",
  },
  {
    id: "candidate_sent",
    projectId: "project_northstar",
    name: "Tandem",
    tagline: "Async product reviews for distributed teams",
    productHuntUrl: "https://www.producthunt.com/posts/tandem-review",
    websiteUrl: "https://tandem.review",
    companyContext:
      "Tandem replaces live product review meetings with contextual, asynchronous feedback rounds.",
    recipientEmail: "hello@tandem.review",
    emailConfidence: 0.91,
    emailEvidenceUrl: "https://tandem.review/contact",
    alternativeEmails: [],
    matchReason: "Shared focus on calm product operations for small teams.",
    subject: "A lighter roadmap handoff for Tandem teams",
    body: "Hi Tandem team,\n\nI’m Kit, Maya’s AI agent at Northstar. Your timed feedback rounds are a thoughtful way to keep reviews moving without a calendar pileup.\n\nNorthstar helps the same teams record the decision before a review begins. Maya wondered whether a small workflow template joining those steps would be useful.\n\nOpen to seeing it?\n\nKit",
    status: "sent",
    completedAt: Date.now() - 48 * 60 * 1000,
  },
  {
    id: "candidate_dismissed",
    projectId: "project_northstar",
    name: "Driftwood",
    tagline: "Personal travel planning with local signals",
    productHuntUrl: "https://www.producthunt.com/posts/driftwood",
    websiteUrl: "https://driftwood.travel",
    companyContext: "A collaborative itinerary builder for leisure travel.",
    recipientEmail: "team@driftwood.travel",
    emailConfidence: 0.84,
    emailEvidenceUrl: "https://driftwood.travel/contact",
    alternativeEmails: [],
    matchReason: "A weak audience overlap was found during final filtering.",
    subject: "A product planning thought for Driftwood",
    body: "Hi Driftwood team,\n\nI’m Kit, Maya’s AI agent at Northstar. I noticed your local signals keep an itinerary grounded as plans change.\n\nNorthstar works with teams on a similar decision rhythm. Would a short template be useful?\n\nKit",
    status: "dismissed",
    completedAt: Date.now() - 3 * 60 * 60 * 1000,
  },
];

export const demoRun: DailyRun = {
  id: "run_demo",
  day: new Date().toISOString().slice(0, 10),
  status: "completed",
  currentStep: "Complete",
  counts: { fetched: 34, eligible: 11, enriched: 8, drafted: 3, failed: 0 },
  startedAt: Date.now() - 75 * 60 * 1000,
  completedAt: Date.now() - 69 * 60 * 1000,
};
